### ISSUE TITLE
swift 3+?

### ISSUE THREAD

**Issue by dkliman** [safx/liquidfun-swift-sample#1]
hi...

any plans to update your repository to swift 3.x or 4?

**Comment by smarques84** [comment]
I tried convert this sample sample project to swift 3 but when running on a real device but it reaches this line
`let pipelineDescriptor = MTLRenderPipelineDescriptor()` i always get the following error

`(LiquidMetal) does not have sandbox access for frZQaeyWLUvLjeuEK43hmg and IS NOT appropriately entitled
2017-06-24 12:10:25.952133+0100 LiquidMetal[236:4874] libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)`

I am tried searching google for this problem but for what i could undertstand the reasons can be many like some kind of incompatibility with iOS 10.3 and the sample not sure, any ideas?

**Comment by safx** [comment]
I upgrade Swift 4.
