### ISSUE TITLE
Migration to Swift 4

### ISSUE THREAD

**Issue by Ermiasmarino** [safx/liquidfun-swift-sample#2]
Hi, I am unable to migrate the code from Swift 3 to Swift 4 as I am on Big Sur and I cannot install Xcode 10. Could you please migrate the code? Thanks. Merry Christmas and Happy New Year.

**Comment by safx** [comment]
@Ermiasmarino Hi, I try to migrate to Swift 4 in develop branch. Could you check it please? I'll merge it to the default branch if it's fine to you, thanks.

**Comment by Ermiasmarino** [comment]
Thank you very much Yuji Matsumoto. It is working perfectly now. I have the greatest respect for Japan, the Japanese people, and you Yuji Matsumoto. You are an inspiration for the rest of the world and you deserve to be on top of the world. I love you. Emmmmmmmmmmmmua 😘. May The Almighty God bless Japan, the Japanese people, and you and your family. Amen 🙏 :).

**Comment by safx** [comment]
Thank you for you testing. I'll close this issue, thanks.

**Comment by Ermiasmarino** [comment]
You are most welcome :).
